# Makefile sample
# following https://www.kernel.org/doc/html/latest/kbuild/makefiles.html
obj-m += module.o # tells kbuild that module.o is to be built as a module, from module.c
obj-y += module.o # tells kbuild that module.o is to be built as a built-in, from module.c
